export const data = [
  {
    id: 1,
    word: "apple",
    translation: "яблоко",
    transcription: "/ˈæp.əl/",
    imageUrl: "../assets/images/apple.jpg",
    tags: ["fruit", "food", "healthy"],
    tags_json: JSON.stringify(["fruit", "food", "healthy"]),
  },
  {
    id: 2,
    word: "banana",
    translation: "банан",
    transcription: "/bəˈnæn.ə/",
    imageUrl: "../assets/images/banana.jpg",
    tags: ["fruit", "food", "tropical"],
    tags_json: JSON.stringify(["fruit", "food", "tropical"]),
  },
  {
    id: 3,
    word: "orange",
    translation: "апельсин",
    transcription: "/ˈɔːr.ɪndʒ/",
    imageUrl: "../assets/images/orange.jpg",
    tags: ["fruit", "food", "citrus"],
    tags_json: JSON.stringify(["fruit", "food", "citrus"]),
  },
  {
    id: 4,
    word: "grape",
    translation: "виноград",
    transcription: "/ɡreɪp/",
    imageUrl: "../assets/images/grape.jpg",
    tags: ["fruit", "food"],
    tags_json: JSON.stringify(["fruit", "food"]),
  },
  {
    id: 5,
    word: "strawberry",
    translation: "клубника",
    transcription: "/ˈstrɔː.bər.i/",
    imageUrl: "../assets/images/strawberry.jpg",
    tags: ["fruit", "food"],
    tags_json: JSON.stringify(["fruit", "food"]),
  },
  {
    id: 6,
    word: "watermelon",
    translation: "арбуз",
    transcription: "/ˈwɔː.tərˌmel.ən/",
    imageUrl: "../assets/images/watermelon.jpg",
    tags: ["fruit", "food", "summer"],
    tags_json: JSON.stringify(["fruit", "food", "summer"]),
  },
  {
    id: 7,
    word: "kiwi",
    translation: "киви",
    transcription: "/ˈkiː.wi/",
    imageUrl: "../assets/images/kiwi.jpg",
    tags: ["fruit', 'food"],
    tags_json: JSON.stringify(["fruit", "food"]),
  },
  {
    id: 8,
    word: "peach",
    translation: "персик",
    transcription: "/piːtʃ/",
    imageUrl: "../assets/images/peach.jpg",
    tags: ["fruit", "food"],
    tags_json: JSON.stringify(["fruit", "food"]),
  },
  {
    id: 9,
    word: "pineapple",
    translation: "ананас",
    transcription: "/ˈpaɪ.næp.əl/",
    imageUrl: "../assets/images/pineapple.jpg",
    tags: ["fruit", "food", "tropical"],
    tags_json: JSON.stringify(["fruit", "food", "tropical"]),
  },
  {
    id: 10,
    word: "mango",
    translation: "манго",
    transcription: "/ˈmæŋ.ɡoʊ/",
    imageUrl: "../assets/images/mango.jpg",
    tags: ["fruit", "food", "tropical"],
    tags_json: JSON.stringify(["fruit", "food", "tropical"]),
  },

  {
    id: 11,
    word: "carrot",
    translation: "морковь",
    transcription: "/ˈkær.ət/",
    imageUrl: "../assets/images/carrot.jpg",
    tags: ["vegetable", "healthy"],
    tags_json: JSON.stringify(["vegetable", "healthy"]),
  },
  {
    id: 12,
    word: "potato",
    translation: "картофель",
    transcription: "/pəˈteɪ.toʊ/",
    imageUrl: "../assets/images/potato.jpg",
    tags: ["vegetable", "starchy"],
    tags_json: JSON.stringify(["vegetable", "starchy"]),
  },
  {
    id: 13,
    word: "tomato",
    translation: "помидор",
    transcription: "/təˈmeɪ.toʊ/",
    imageUrl: "../assets/images/tomato.jpg",
    tags: ["vegetable", "salad"],
    tags_json: JSON.stringify(["vegetable", "salad"]),
  },
  {
    id: 14,
    word: "cucumber",
    translation: "огурец",
    transcription: "/ˈkjuː.kəm.bər/",
    imageUrl: "../assets/images/cucumber.jpg",
    tags: ["vegetable", "salad"],
    tags_json: JSON.stringify(["vegetable", "salad"]),
  },
  {
    id: 15,
    word: "broccoli",
    translation: "брокколи",
    transcription: "/ˈbrɒk.ə.li/",
    imageUrl: "../assets/images/broccoli.jpg",
    tags: ["vegetable", "healthy"],
    tags_json: JSON.stringify(["vegetable", "healthy"]),
  },
];
